In [1]:
import pandas as pd

In [2]:
def inspect_df(df, name):
    """
    Display useful information about a dataframe
    """

    print("=" * 60)
    print(f"DATAFRAME: {name}")
    print("=" * 60)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nFirst 5 Rows:")
    print(df.head())

    print("\n")

In [3]:
food_df = pd.read_csv(
    "../food_data/raw/food.csv"
)

In [4]:
food_df.head()

,fdc_id,data_type,description,food_category_id,publication_date
0,319874,sample_food,"HUMMUS, SABRA CLASSIC",16.0,2019-04-01
1,319875,market_acquisition,"HUMMUS, SABRA CLASSIC",16.0,2019-04-01
2,319876,market_acquisition,"HUMMUS, SABRA CLASSIC",16.0,2019-04-01
3,319877,sub_sample_food,Hummus,16.0,2019-04-01
4,319878,sub_sample_food,Hummus,16.0,2019-04-01

In [5]:
inspect_df(
    food_df,
    "FOOD DATASET"
)

============================================================
DATAFRAME: FOOD DATASET
============================================================

Shape:
(87990, 5)

Columns:
['fdc_id', 'data_type', 'description', 'food_category_id', 'publication_date']

Data Types:
fdc_id                int64
data_type               str
description             str
food_category_id    float64
publication_date        str
dtype: object

Missing Values:
fdc_id                 0
data_type              0
description            8
food_category_id    3811
publication_date       0
dtype: int64

First 5 Rows:
   fdc_id           data_type            description  food_category_id  \
0  319874         sample_food  HUMMUS, SABRA CLASSIC              16.0
1  319875  market_acquisition  HUMMUS, SABRA CLASSIC              16.0
2  319876  market_acquisition  HUMMUS, SABRA CLASSIC              16.0
3  319877     sub_sample_food                 Hummus              16.0
4  319878     sub_sample_food                 Hummus              16.0

  publication_date
0       2019-04-01
1       2019-04-01
2       2019-04-01
3       2019-04-01
4       2019-04-01

In [6]:
food_df["fdc_id"].nunique()

87990

In [7]:
len(food_df)

87990

In [8]:
food_df["data_type"].value_counts()

data_type
sub_sample_food             75055
market_acquisition           7577
sample_food                  4079
agricultural_acquisition      810
foundation_food               469
Name: count, dtype: int64

In [9]:
food_df[
    food_df["description"].isna()
]

        fdc_id        data_type description  food_category_id publication_date
27553  1757383  sub_sample_food         NaN              16.0       2021-04-23
27554  1757384  sub_sample_food         NaN              16.0       2021-04-23
27555  1757385  sub_sample_food         NaN              16.0       2021-04-23
27556  1757386  sub_sample_food         NaN              16.0       2021-04-23
27557  1757387  sub_sample_food         NaN              16.0       2021-04-23
27558  1757388  sub_sample_food         NaN              16.0       2021-04-23
27559  1757389  sub_sample_food         NaN              16.0       2021-04-23
27560  1757390  sub_sample_food         NaN              16.0       2021-04-23

In [10]:
(
    food_df["food_category_id"]
    .isna()
    .mean()
) * 100

np.float64(4.331173997045119)

In [11]:
food_df[
    food_df["publication_date"].str.contains("/")
]["publication_date"].head(20)

55224    7/19/2023
55225    7/21/2023
55226    8/14/2023
55227    8/16/2023
55228     6/2/2023
55229    6/21/2023
55230    7/19/2023
55231    6/12/2023
55232    7/12/2023
55233    8/10/2023
55234    8/14/2023
55235    8/16/2023
55236    7/21/2023
55237    8/10/2023
55238    8/14/2023
55239    8/16/2023
55240     6/2/2023
55241    6/16/2023
55242    7/12/2023
55243    6/12/2023
Name: publication_date, dtype: str

In [12]:
food_df["publication_date"] = pd.to_datetime(
    food_df["publication_date"],
    format="mixed",
    errors="coerce"
)

In [13]:
food_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 87990 entries, 0 to 87989
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fdc_id            87990 non-null  int64
 1   data_type         87990 non-null  str
 2   description       87982 non-null  str
 3   food_category_id  84179 non-null  float64
 4   publication_date  87990 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(2)
memory usage: 3.4 MB

In [14]:
food_df["fdc_id"].nunique()

87990

In [15]:
len(food_df)

87990

In [16]:
food_df["data_type"].value_counts()

data_type
sub_sample_food             75055
market_acquisition           7577
sample_food                  4079
agricultural_acquisition      810
foundation_food               469
Name: count, dtype: int64

In [17]:
food_df.groupby("data_type").agg({
    "fdc_id": "count"
})

                          fdc_id
data_type
agricultural_acquisition     810
foundation_food              469
market_acquisition          7577
sample_food                 4079
sub_sample_food            75055

In [18]:
food_category_df = pd.read_csv(
    "../food_data/raw/food_category.csv"
)

In [19]:
inspect_df(
    food_category_df,
    "FOOD CATEGORY"
)

============================================================
DATAFRAME: FOOD CATEGORY
============================================================

Shape:
(28, 3)

Columns:
['id', 'code', 'description']

Data Types:
id             int64
code           int64
description      str
dtype: object

Missing Values:
id             0
code           0
description    0
dtype: int64

First 5 Rows:
   id  code             description
0   1   100  Dairy and Egg Products
1   2   200        Spices and Herbs
2   3   300              Baby Foods
3   4   400           Fats and Oils
4   5   500        Poultry Products

In [20]:
food_category_df.head(20)

    id  code                        description
0    1   100             Dairy and Egg Products
1    2   200                   Spices and Herbs
2    3   300                         Baby Foods
3    4   400                      Fats and Oils
4    5   500                   Poultry Products
5    6   600         Soups, Sauces, and Gravies
6    7   700        Sausages and Luncheon Meats
7    8   800                  Breakfast Cereals
8    9   900            Fruits and Fruit Juices
9   10  1000                      Pork Products
10  11  1100  Vegetables and Vegetable Products
11  12  1200              Nut and Seed Products
12  13  1300                      Beef Products
13  14  1400                          Beverages
14  15  1500     Finfish and Shellfish Products
15  16  1600        Legumes and Legume Products
16  17  1700      Lamb, Veal, and Game Products
17  18  1800                     Baked Products
18  19  1900                             Sweets
19  20  2000            Cereal Grains and Pasta

In [21]:
food_with_category_df = pd.merge(
    food_df,
    food_category_df,
    left_on="food_category_id",
    right_on="id",
    how="left",
    suffixes=("_food", "_category")
)

In [22]:
food_with_category_df.shape

(87990, 8)

In [23]:
food_with_category_df.columns.tolist()

['fdc_id',
 'data_type',
 'description_food',
 'food_category_id',
 'publication_date',
 'id',
 'code',
 'description_category']

In [24]:
food_with_category_df[
    [
        "fdc_id",
        "description_food",
        "description_category"
    ]
].head(20)

    fdc_id       description_food         description_category
0   319874  HUMMUS, SABRA CLASSIC  Legumes and Legume Products
1   319875  HUMMUS, SABRA CLASSIC  Legumes and Legume Products
2   319876  HUMMUS, SABRA CLASSIC  Legumes and Legume Products
3   319877                 Hummus  Legumes and Legume Products
4   319878                 Hummus  Legumes and Legume Products
5   319879  HUMMUS, SABRA CLASSIC  Legumes and Legume Products
6   319880  HUMMUS, SABRA CLASSIC  Legumes and Legume Products
7   319881  HUMMUS, SABRA CLASSIC  Legumes and Legume Products
8   319882                 Hummus  Legumes and Legume Products
9   319883                 Hummus  Legumes and Legume Products
10  319884                 Hummus  Legumes and Legume Products
11  319885  HUMMUS, SABRA CLASSIC  Legumes and Legume Products
12  319886  HUMMUS, SABRA CLASSIC  Legumes and Legume Products
13  319887  HUMMUS, SABRA CLASSIC  Legumes and Legume Products
14  319888  HUMMUS, SABRA CLASSIC  Legumes and Legume Products
15  319889  HUMMUS, SABRA CLASSIC  Legumes and Legume Products
16  319890  HUMMUS, SABRA CLASSIC  Legumes and Legume Products
17  319891  HUMMUS, SABRA CLASSIC  Legumes and Legume Products
18  319892                 Hummus  Legumes and Legume Products
19  319893                 Hummus  Legumes and Legume Products

In [25]:
food_nutrient_df = pd.read_csv(
    "../food_data/raw/food_nutrient.csv",
    low_memory=False
)

In [26]:
inspect_df(
    food_nutrient_df,
    "FOOD NUTRIENT"
)

============================================================
DATAFRAME: FOOD NUTRIENT
============================================================

Shape:
(170469, 11)

Columns:
['id', 'fdc_id', 'nutrient_id', 'amount', 'data_points', 'derivation_id', 'min', 'max', 'median', 'footnote', 'min_year_acquired']

Data Types:
id                     int64
fdc_id                 int64
nutrient_id            int64
amount               float64
data_points          float64
derivation_id        float64
min                  float64
max                  float64
median               float64
footnote                 str
min_year_acquired    float64
dtype: object

Missing Values:
id                        0
fdc_id                    0
nutrient_id               0
amount                   33
data_points            3651
derivation_id           431
min                  152888
max                  152888
median               152286
footnote             170447
min_year_acquired    138171
dtype: int64

First 5 Rows:
        id  fdc_id  nutrient_id  amount  data_points  derivation_id  min  max  \
0  2201847  319877         1051   56.30          1.0            1.0  NaN  NaN
1  2201845  319877         1002    1.28          1.0            1.0  NaN  NaN
2  2201846  319877         1004   19.00          1.0            1.0  NaN  NaN
3  2201844  319877         1007    1.98          1.0            1.0  NaN  NaN
4  2201852  319878         1091  188.00          1.0            1.0  NaN  NaN

   median footnote  min_year_acquired
0     NaN      NaN                NaN
1     NaN      NaN                NaN
2     NaN      NaN                NaN
3     NaN      NaN                NaN
4     NaN      NaN                NaN

In [27]:
food_nutrient_df.head(10)

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired
0,2201847,319877,1051,56.30,1.0,1.0,NaN,NaN,NaN,NaN,NaN
1,2201845,319877,1002,1.28,1.0,1.0,NaN,NaN,NaN,NaN,NaN
2,2201846,319877,1004,19.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN
3,2201844,319877,1007,1.98,1.0,1.0,NaN,NaN,NaN,NaN,NaN
4,2201852,319878,1091,188.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN
5,2201851,319878,1101,1.21,1.0,1.0,NaN,NaN,NaN,NaN,NaN
6,2201853,319878,1092,326.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN
7,2201848,319878,1087,46.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN
8,2201854,319878,1093,446.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN
9,2201850,319878,1090,75.90,1.0,1.0,NaN,NaN,NaN,NaN,NaN

In [28]:
nutrient_df = pd.read_csv(
    "../food_data/raw/nutrient.csv"
)

In [29]:
inspect_df(
    nutrient_df,
    "NUTRIENT"
)

============================================================
DATAFRAME: NUTRIENT
============================================================

Shape:
(477, 5)

Columns:
['id', 'name', 'unit_name', 'nutrient_nbr', 'rank']

Data Types:
id                int64
name                str
unit_name           str
nutrient_nbr    float64
rank            float64
dtype: object

Missing Values:
id               0
name             0
unit_name        0
nutrient_nbr    12
rank            11
dtype: int64

First 5 Rows:
     id                               name unit_name  nutrient_nbr   rank
0  2047   Energy (Atwater General Factors)      KCAL         957.0  280.0
1  2048  Energy (Atwater Specific Factors)      KCAL         958.0  290.0
2  1001                             Solids         G         201.0  200.0
3  1002                           Nitrogen         G         202.0  500.0
4  1003                            Protein         G         203.0  600.0

In [30]:
nutrient_df.head(20)

,id,name,unit_name,nutrient_nbr,rank
0,2047,Energy (Atwater General Factors),KCAL,957.0,280.0
1,2048,Energy (Atwater Specific Factors),KCAL,958.0,290.0
2,1001,Solids,G,201.0,200.0
3,1002,Nitrogen,G,202.0,500.0
4,1003,Protein,G,203.0,600.0
5,1004,Total lipid (fat),G,204.0,800.0
6,1005,"Carbohydrate, by difference",G,205.0,1110.0
7,1006,"Fiber, crude (DO NOT USE - Archived)",G,206.0,999999.0
8,1007,Ash,G,207.0,1000.0
9,1008,Energy,KCAL,208.0,300.0
10,1009,Starch,G,209.0,2200.0
11,1010,Sucrose,G,210.0,1600.0
12,1011,Glucose,G,211.0,1700.0
13,1012,Fructose,G,212.0,1800.0
14,1013,Lactose,G,213.0,1900.0
15,1014,Maltose,G,214.0,2000.0
16,1015,Amylose,G,218.0,999999.0
17,1016,Amylopectin,G,219.0,999999.0
18,1017,Pectin,G,220.0,999999.0
19,1018,"Alcohol, ethyl",G,221.0,18200.0

In [31]:
nutrient_df[
    nutrient_df["name"].str.contains(
        "Protein|Energy|Carbohydrate|fat",
        case=False,
        na=False
    )
]

,id,name,unit_name,nutrient_nbr,rank
0,2047,Energy (Atwater General Factors),KCAL,957.0,280.0
1,2048,Energy (Atwater Specific Factors),KCAL,958.0,290.0
4,1003,Protein,G,203.0,600.0
5,1004,Total lipid (fat),G,204.0,800.0
6,1005,"Carbohydrate, by difference",G,205.0,1110.0
9,1008,Energy,KCAL,208.0,300.0
50,1049,"Solids, non-fat",G,253.0,999999.0
51,1050,"Carbohydrate, by summation",G,205.2,1120.0
54,1053,Adjusted Protein,G,257.0,700.0
63,1062,Energy,kJ,268.0,400.0
73,1072,"Carbohydrate, other",G,284.0,NaN
86,1085,Total fat (NLEA),G,298.0,900.0
258,1257,"Fatty acids, total trans",G,605.0,15400.0
259,1258,"Fatty acids, total saturated",G,606.0,9700.0
291,1291,"Fatty acids, other than 607-615, 617-621, 624-...",G,644.0,999999.0
292,1292,"Fatty acids, total monounsaturated",G,645.0,11400.0
293,1293,"Fatty acids, total polyunsaturated",G,646.0,12900.0
318,1318,"Fatty acids, saturated, other",G,677.0,999999.0
319,1319,"Fatty acids, monounsat., other",G,678.0,999999.0
320,1320,"Fatty acids, polyunsat., other",G,679.0,999999.0
326,1326,"Fatty acids, total sat., NLEA",G,690.0,999999.0
327,1327,"Fatty acids, total monounsat., NLEA",G,691.0,999999.0
328,1328,"Fatty acids, total polyunsat., NLEA",G,692.0,999999.0
329,1329,"Fatty acids, total trans-monoenoic",G,693.0,15500.0
330,1330,"Fatty acids, total trans-dienoic",G,694.0,15601.0
331,1331,"Fatty acids, total trans-polyenoic",G,695.0,15619.0
450,2039,Carbohydrates,G,956.0,1100.0

In [32]:
food_nutrient_with_name_df = pd.merge(
    food_nutrient_df,
    nutrient_df,
    left_on="nutrient_id",
    right_on="id",
    how="left",
    suffixes=("", "_nutrient")
)

In [33]:
food_nutrient_with_name_df[
    [
        "fdc_id",
        "nutrient_id",
        "name",
        "amount",
        "unit_name"
    ]
].head(20)

    fdc_id  nutrient_id               name  amount unit_name
0   319877         1051              Water   56.30         G
1   319877         1002           Nitrogen    1.28         G
2   319877         1004  Total lipid (fat)   19.00         G
3   319877         1007                Ash    1.98         G
4   319878         1091      Phosphorus, P  188.00        MG
5   319878         1101      Manganese, Mn    1.21        MG
6   319878         1092       Potassium, K  326.00        MG
7   319878         1087        Calcium, Ca   46.00        MG
8   319878         1093         Sodium, Na  446.00        MG
9   319878         1090      Magnesium, Mg   75.90        MG
10  319878         1089           Iron, Fe    2.33        MG
11  319878         1098         Copper, Cu    0.38        MG
12  319878         1095           Zinc, Zn    1.50        MG
13  319882         1051              Water   56.10         G
14  319882         1007                Ash    1.99         G
15  319882         1002           Nitrogen    1.29         G
16  319882         1004  Total lipid (fat)   18.70         G
17  319883         1170   Pantothenic acid    0.37        MG
18  319884         1101      Manganese, Mn    1.20        MG
19  319884         1093         Sodium, Na  444.00        MG

In [34]:
protein_df = food_nutrient_with_name_df[
    food_nutrient_with_name_df["name"] == "Protein"
]

In [35]:
protein_df.head()

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired,id_nutrient,name,unit_name,nutrient_nbr,rank
2105,2204224,320356,1003,23.4,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1003.0,Protein,G,203.0,600.0
2119,2204238,320383,1003,23.9,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1003.0,Protein,G,203.0,600.0
2150,2204272,320389,1003,23.5,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1003.0,Protein,G,203.0,600.0
2154,2204276,320391,1003,23.8,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1003.0,Protein,G,203.0,600.0
2160,2204280,320393,1003,23.8,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1003.0,Protein,G,203.0,600.0

In [36]:
protein_foods_df = pd.merge(
    protein_df,
    food_df,
    on="fdc_id",
    how="left"
)

In [37]:
protein_foods_df = protein_foods_df[
    [
        "fdc_id",
        "description",
        "amount"
    ]
]

In [38]:
protein_foods_df = protein_foods_df.rename(
    columns={
        "amount": "protein_g"
    }
)

In [39]:
protein_foods_df.sort_values(
    by="protein_g",
    ascending=False
).head(20)

       fdc_id                                        description  protein_g
26     323793                                  Egg, white, dried   79.90000
1133  1104705                               Flour, soy, defatted   51.10000
54     329490                                  Egg, whole, dried   48.10000
1108   749420             Pork, cured, bacon, cooked, restaurant   40.90000
1134  1104766                               Flour, soy, full-fat   38.60000
56     329716                                   Egg, yolk, dried   34.20000
122    331960  Chicken, broiler or fryers, breast, skinless, ...   32.10000
957    335969      Beans, Dry, Great Northern, 446 (0% moisture)   31.60000
583    335595               Beans, Dry, Pinto, 468 (0% moisture)   30.80000
960    335972      Beans, Dry, Great Northern, 579 (0% moisture)   30.50000
209    335052  Proximates, Beef, T-Bone Steak, lean only, coo...   30.40000
1200  2259795             Cheese, parmesan, grated, refrigerated   30.13912
1269  2515380                Seeds, pumpkin seeds (pepitas), raw   29.90790
210    335054  Proximates, Beef, T-Bone Steak, lean only, coo...   29.90000
32     325036                           Cheese, parmesan, grated   29.60000
493    335505               Beans, Dry, Pinto, 465 (0% moisture)   29.40000
966    335978      Beans, Dry, Great Northern, 581 (0% moisture)   29.40000
594    335606               Beans, Dry, Pinto, 787 (0% moisture)   29.40000
442    335454          Beans, Dry, Pinto, 11F-8114 (0% moisture)   29.20000
170    334888  Proximates, Beef, Tenderloin Roast, lean only,...   29.10000

In [40]:
import sys
from pathlib import Path

In [41]:
sys.path.append(
    str(Path().resolve().parent)
)

In [42]:
from src.data_loader import DataLoader

In [43]:
loader = DataLoader()

In [44]:
food_df = loader.load_foods()

food_df.head()

,fdc_id,data_type,description,food_category_id,publication_date
0,319874,sample_food,"HUMMUS, SABRA CLASSIC",16.0,2019-04-01
1,319875,market_acquisition,"HUMMUS, SABRA CLASSIC",16.0,2019-04-01
2,319876,market_acquisition,"HUMMUS, SABRA CLASSIC",16.0,2019-04-01
3,319877,sub_sample_food,Hummus,16.0,2019-04-01
4,319878,sub_sample_food,Hummus,16.0,2019-04-01

In [45]:
project_root = Path().resolve().parent

In [46]:
print(project_root)

C:\Learning-new things\Food Insights Engine

In [47]:
from src.cleaner import NutritionCleaner

In [48]:
cleaner = NutritionCleaner()

In [49]:
cleaner.get_basic_summary(food_df)

{'rows': 87990, 'columns': 5, 'duplicates': np.int64(0), 'missing_cells': 3819}

In [50]:
missing_report = cleaner.get_missing_values_report(
    food_df
)

missing_report

             column  missing_count  missing_percentage
3  food_category_id           3811                4.33
2       description              8                0.01
0            fdc_id              0                0.00
1         data_type              0                0.00
4  publication_date              0                0.00

In [51]:
from src.analyzer import NutritionAnalyzer

In [52]:
analyzer = NutritionAnalyzer()

In [53]:
top_protein_foods = analyzer.get_top_protein_foods(
    food_df=food_df,
    food_nutrient_df=food_nutrient_df,
    top_n=20
)

In [54]:
top_protein_foods

       fdc_id                                        description  protein_g
26     323793                                  Egg, white, dried   79.90000
1133  1104705                               Flour, soy, defatted   51.10000
54     329490                                  Egg, whole, dried   48.10000
1108   749420             Pork, cured, bacon, cooked, restaurant   40.90000
1134  1104766                               Flour, soy, full-fat   38.60000
56     329716                                   Egg, yolk, dried   34.20000
122    331960  Chicken, broiler or fryers, breast, skinless, ...   32.10000
957    335969      Beans, Dry, Great Northern, 446 (0% moisture)   31.60000
583    335595               Beans, Dry, Pinto, 468 (0% moisture)   30.80000
960    335972      Beans, Dry, Great Northern, 579 (0% moisture)   30.50000
209    335052  Proximates, Beef, T-Bone Steak, lean only, coo...   30.40000
1200  2259795             Cheese, parmesan, grated, refrigerated   30.13912
1269  2515380                Seeds, pumpkin seeds (pepitas), raw   29.90790
210    335054  Proximates, Beef, T-Bone Steak, lean only, coo...   29.90000
32     325036                           Cheese, parmesan, grated   29.60000
493    335505               Beans, Dry, Pinto, 465 (0% moisture)   29.40000
966    335978      Beans, Dry, Great Northern, 581 (0% moisture)   29.40000
594    335606               Beans, Dry, Pinto, 787 (0% moisture)   29.40000
442    335454          Beans, Dry, Pinto, 11F-8114 (0% moisture)   29.20000
170    334888  Proximates, Beef, Tenderloin Roast, lean only,...   29.10000

In [55]:
food_nutrient_df = loader.load_food_nutrients()
nutrient_df = loader.load_nutrients()
food_category_df = loader.load_food_categories()

In [56]:
top_protein_foods = analyzer.get_top_protein_foods(
    food_df,
    food_nutrient_df
)

top_protein_foods.head()

       fdc_id                             description  protein_g
26     323793                       Egg, white, dried       79.9
1133  1104705                    Flour, soy, defatted       51.1
54     329490                       Egg, whole, dried       48.1
1108   749420  Pork, cured, bacon, cooked, restaurant       40.9
1134  1104766                    Flour, soy, full-fat       38.6

In [57]:
top_calorie_foods = analyzer.get_top_calorie_foods(
    food_df,
    food_nutrient_df
)

top_calorie_foods.head()

    fdc_id                                        description  calories
48  330458                                       Oil, coconut     833.0
44  329716                                   Egg, yolk, dried     654.0
9   323294        Nuts, almonds, dry roasted, with salt added     620.0
24  325524  Seeds, sunflower seed kernels, dry roasted, wi...     612.0
19  324860             Peanut butter, smooth style, with salt     597.0

In [58]:
summary = analyzer.get_dataset_summary(
    food_df,
    food_nutrient_df
)

summary

{'total_foods': 87990,
 'total_nutrient_records': 170469,
 'unique_foods_with_nutrients': 76036,
 'unique_nutrients': 235}

In [59]:
from src.report_generator import ReportGenerator

In [60]:
report_generator = ReportGenerator()

In [61]:
report_generator.export_dataframe(
    top_protein_foods,
    "top_protein_foods.csv"
)

'C:\\Learning-new things\\Food Insights Engine\\reports\\top_protein_foods.csv'

In [63]:
report_generator.export_dataframe(
    top_calorie_foods,
    "top_calorie_foods.csv"
)

'C:\\Learning-new things\\Food Insights Engine\\reports\\top_calorie_foods.csv'

In [64]:
summary = analyzer.get_dataset_summary(
    food_df,
    food_nutrient_df
)

report_generator.generate_summary_report(
    summary
)

'C:\\Learning-new things\\Food Insights Engine\\reports\\nutrition_summary.txt'

In [66]:
from src.visualizer import NutritionVisualizer

visualizer = NutritionVisualizer()

In [67]:
visualizer.plot_top_nutrient_foods(
    df=top_protein_foods,
    value_column="protein_g",
    chart_title="Top Protein Foods",
    output_filename="top_protein_foods.png"
)

In [71]:
visualizer.plot_top_nutrient_foods(
    df=top_calorie_foods,
    value_column="calories",
    chart_title="Top Calorie Foods",
    output_filename="top_calorie_foods.png"
)

In [72]:
food_with_category_df = food_df.merge(
    food_category_df,
    left_on="food_category_id",
    right_on="id",
    how="left",
    suffixes=(
        "_food",
        "_category"
    )
)

In [73]:
visualizer.plot_category_distribution(
    food_with_category_df
)